### PR TITLE
8331331: :tier1 target explanation in doc/testing.md is incorrect

### PR DESCRIPTION
**Pull request by sendaoYan**
Hi,
  This is clean backport of [JDK-8331331](https://bugs.openjdk.org/browse/JDK-8331331), fixed the incorrect explanation :tier1 target in doc/testing.md. No risk.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] [JDK-8331331](https://bugs.openjdk.org/browse/JDK-8331331) needs maintainer approval

### Issue
 * [JDK-8331331](https://bugs.openjdk.org/browse/JDK-8331331): :tier1 target explanation in doc/testing.md is incorrect (**Bug** - P4 - Approved)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk22u.git pull/183/head:pull/183` \
`$ git checkout pull/183`

Update a local copy of the PR: \
`$ git checkout pull/183` \
`$ git pull https://git.openjdk.org/jdk22u.git pull/183/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 183`

View PR using the GUI difftool: \
`$ git pr show -t 183`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk22u/pull/183.diff">https://git.openjdk.org/jdk22u/pull/183.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk22u/pull/183#issuecomment-2093324195)

### CODE REVIEW

**Comment by sendaoYan** [comment]
/approval request This is clean backport of [JDK-8331331](https://bugs.openjdk.org/browse/JDK-8331331), fixed the incorrect explanation :tier1 target in doc/testing.md. No risk.

**Comment by sendaoYan** [comment]
The GHA test [runner](https://github.com/openjdk-bots/jdk22u/actions/runs/9060702404/job/24896412402) complain `java/util/zip/ZipFile/ZipSourceCache.java` intermittent fails on windows-x64. This failure unreleated to this PR. I creat a new [PR](https://github.com/openjdk/jdk22u/pull/201) to fix this intermittent failure.

**Comment by shipilev** [comment]
I believe GHA failures are environmental.

/sponsor

**Pull request closed without merging**
