### PR TITLE
8321489: Update LCMS to 2.16

### PR DESCRIPTION
**Pull request by alisenchung**
Backport of dc7d3b182d226253ca246dd854c85c4dd964f10e

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] [JDK-8321489](https://bugs.openjdk.org/browse/JDK-8321489) needs maintainer approval

### Issue
 * [JDK-8321489](https://bugs.openjdk.org/browse/JDK-8321489): Update LCMS to 2.16 (**Bug** - P3 - Approved)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk22u.git pull/32/head:pull/32` \
`$ git checkout pull/32`

Update a local copy of the PR: \
`$ git checkout pull/32` \
`$ git pull https://git.openjdk.org/jdk22u.git pull/32/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 32`

View PR using the GUI difftool: \
`$ git pr show -t 32`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk22u/pull/32.diff">https://git.openjdk.org/jdk22u/pull/32.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk22u/pull/32#issuecomment-1911041152)

### CODE REVIEW

**Comment by prrace** [comment]
> "Issue of type Backport is not allowed for integrations"

I think this is because you used the backport ID in the PR
You need to use the main bug ID and skara will create / use the backport ID when integrating.

Actually it doesn't look to me like you did this as a backport at all ..

**Comment by kevinrushforth** [comment]
@alisenchung The problem is that you manually edited the title, when the one Skara suggested is the one you need to use. To fix this, edit the title to use the one Skara suggested:

```
Backport dc7d3b182d226253ca246dd854c85c4dd964f10e
```

**Comment by GoeLin** [comment]
Hi, 
thanks for picking this up. It need to be backported to 21, 17 and 11.
Maybe you want to have a look at the instruction in https://wiki.openjdk.org/display/JDKUpdates/How+to+contribute+or+backport+a+fix
We ususally backport these changes to the same release as Oracle does. And as they did not do so yet, it's maybe a bit early for this.

**Comment by kevinrushforth** [comment]
@GoeLin Alisen works for Oracle and will be doing the backports to the Oracle releases soon. You might look to someone else in the OpenJDK community to pick this up for OpenJDK 21u, 17u, and 11u

**Comment by GoeLin** [comment]
@alisenchung @kevinrushforg ah, you are right, it's 22 not 21 ... but looking at the doc might be helpful anyways.

**Pull request closed without merging**
