### PR TITLE
8325203: System.exit(0) kills the launched 3rd party application

### PR DESCRIPTION
**Pull request by alexeysemenyukoracle**
---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] [JDK-8325203](https://bugs.openjdk.org/browse/JDK-8325203) needs maintainer approval

### Issue
 * [JDK-8325203](https://bugs.openjdk.org/browse/JDK-8325203): System.exit(0) kills the launched 3rd party application (**Bug** - P3 - Approved)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk22u.git pull/49/head:pull/49` \
`$ git checkout pull/49`

Update a local copy of the PR: \
`$ git checkout pull/49` \
`$ git pull https://git.openjdk.org/jdk22u.git pull/49/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 49`

View PR using the GUI difftool: \
`$ git pr show -t 49`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk22u/pull/49.diff">https://git.openjdk.org/jdk22u/pull/49.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk22u/pull/49#issuecomment-1936441761)

### CODE REVIEW

**Comment by sblantipodi** [comment]
@alexeysemenyukoracle I'm sorry if I quote you, 
may I ask if this fix has been released with the current JDK 22 release?

**Comment by kevinrushforth** [comment]
> @alexeysemenyukoracle I'm sorry if I quote you, may I ask if this fix has been released with the current JDK 22 release?

I'm not Alexey, but I can answer this. As can be seen in the [JBS issue](https://bugs.openjdk.org/browse/JDK-8325203), this fix was backported to JDK 22.0.1. The release date for 22.0.1 is April 16, 2024.

**Comment by sblantipodi** [comment]
thanks Kevin, I really appreciate your work in the Java community.  👍

**Pull request closed without merging**
