### PR TITLE
8323008: filter out harmful -std* flags added by autoconf from CXX

### PR DESCRIPTION
**Pull request by MBaesken**
---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [ ] [JDK-8323008](https://bugs.openjdk.org/browse/JDK-8323008) needs maintainer approval

### Issue
 * [JDK-8323008](https://bugs.openjdk.org/browse/JDK-8323008): filter out harmful -std* flags added by autoconf from CXX (**Bug** - P3)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk22u.git pull/20/head:pull/20` \
`$ git checkout pull/20`

Update a local copy of the PR: \
`$ git checkout pull/20` \
`$ git pull https://git.openjdk.org/jdk22u.git pull/20/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 20`

View PR using the GUI difftool: \
`$ git pr show -t 20`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk22u/pull/20.diff">https://git.openjdk.org/jdk22u/pull/20.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk22u/pull/20#issuecomment-1889110569)

### CODE REVIEW

**Comment by TheShermanTanker** [comment]
Could you hold this backport for a moment?
https://github.com/openjdk/jdk/pull/17401

**Comment by MBaesken** [comment]
> Could you hold this backport for a moment? [openjdk/jdk#17401](https://github.com/openjdk/jdk/pull/17401)

okay, the GHA#s are not doing well currently anyway ...

**Comment by TheShermanTanker** [comment]
> > Could you hold this backport for a moment? [openjdk/jdk#17401](https://github.com/openjdk/jdk/pull/17401)
> 
> okay, the GHA#s are not doing well currently anyway ...

Yeah, no idea what's causing JTReg to explode on GHAs at the moment :/

**Comment by RealCLanger** [comment]
Can we please close this in favour of the backport to jdk22: https://github.com/openjdk/jdk22/pull/70

It's a P3 fix, eligible under RDP1 rules. And I'd like to have the flags filtered out in all builds wherever possible.

@TheShermanTanker did you spot any problem with the change, except for the GHA issues?

**Comment by TheShermanTanker** [comment]
@RealCLanger Nope, looks ok to me (Hopefully we can come up with a better solution to this problem in the future though...)

**Pull request closed without merging**
