### PR TITLE
8322417: Console read line with zero out should zero out when throwing exception

### PR DESCRIPTION
**Pull request by RealCLanger**
Hi all,

This pull request contains a backport of [JDK-8322417](https://bugs.openjdk.org/browse/JDK-8322417), commit [2f917bff](https://github.com/openjdk/jdk/commit/2f917bff5cbb71dccd70960f563ca1a05d109fda) from the [openjdk/jdk](https://git.openjdk.org/jdk) repository.

The commit being backported was authored by Goetz Lindenmaier on 20 Dec 2023 and was reviewed by Matthias Baesken, Thomas Stuefe and Naoto Sato.

Thanks!

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] [JDK-8322772](https://bugs.openjdk.org/browse/JDK-8322772) needs maintainer approval
- [x] [JDK-8322417](https://bugs.openjdk.org/browse/JDK-8322417) needs maintainer approval

### Issues
 * [JDK-8322417](https://bugs.openjdk.org/browse/JDK-8322417): Console read line with zero out should zero out when throwing exception (**Bug** - P4 - Approved)
 * [JDK-8322772](https://bugs.openjdk.org/browse/JDK-8322772): Clean up code after JDK-8322417 (**Bug** - P4 - Approved)

### Reviewers
 * [Matthias Baesken](https://openjdk.org/census#mbaesken) (@MBaesken - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk22u.git pull/7/head:pull/7` \
`$ git checkout pull/7`

Update a local copy of the PR: \
`$ git checkout pull/7` \
`$ git pull https://git.openjdk.org/jdk22u.git pull/7/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 7`

View PR using the GUI difftool: \
`$ git pr show -t 7`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk22u/pull/7.diff">https://git.openjdk.org/jdk22u/pull/7.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk22u/pull/7#issuecomment-1872096870)

### CODE REVIEW

**Comment by RealCLanger** [comment]
/approval request Requesting this backport to clear out data in another possible path in JConsole password handling. Testing: SAP nightlies, GHA.

**Comment by RealCLanger** [comment]
/approval JDK-8322772 request Requesting as inline part of the backport of [JDK-8322417](https://bugs.openjdk.org/browse/JDK-8322417).

**Review by MBaesken — APPROVED** [review]

**Pull request closed without merging**
